# Generated by Django 3.2.5 on 2021-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210715_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='area_code',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
