# Generated by Django 3.2.5 on 2021-07-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20210715_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cep',
            field=models.CharField(default=1, max_length=9),
            preserve_default=False,
        ),
    ]
