# Generated by Django 3.2.5 on 2021-07-08 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100)),
                ('data_create', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companys',
            },
        ),
    ]
